[Variables]
Color=200,200,200
;Color of the skins

Scale_Complex=1
;Scale of the complex number clock

Scale_Intergral=1
;Scale of the intergral clock

Complex_Time=S
;Time which you to want display on the clock
;"I" for Hour in 12-hour format
;"H" for Hour in 24-hour format
;"M" for Minutes
;"S" for Seconds

Max_Time=60
;Maximum number of the choosen time
;e.g.:
;for Seconds and Minutes, it's 60
;for 24-hour and 12-hour, it's 24 and 12 respectively
